[project]
name = "persistenciat3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dnspython>=2.7.0",
    "fastapi[standard]>=0.115.8",
    "motor[srv]>=3.7.0",
    "odmantic>=1.0.2",
]
